const peoples = [
    {"id":1, "team":1,"first_name":"Gary","last_name":"Ortiz","age":20,"city":"Wrocław","district":"Gaj","glasses":false},
    {"id":2,"team":1,"first_name":"Albert","last_name":"Williamson","age":21,"city":"Wrocław","district":"Południe","glasses":true},
    {"id":3,"team":1,"first_name":"Mildred","last_name":"Fuller","age":33,"city":"Wrocław","district":"Stare miasto","glasses":true},
    {"id":4,"team":1,"first_name":"Russell","last_name":"Robinson","age":32,"city":"Wrocław","district":"Swojczyce","glasses":false},
    {"id":5,"team":1,"first_name":"Laura","last_name":"Harper","age":21,"city":"Wrocław","district":"Świniary","glasses":false},
    {"id":6,"team":1,"first_name":"Larry","last_name":"Sanders","age":23,"city":"Wrocław","district":"Strachowice","glasses":false},
    {"id":7,"team":1,"first_name":"Michael","last_name":"Rice","age":42,"city":"Wrocław","district":"Pilczyce","glasses":true},
    {"id":8,"team":1,"first_name":"Sara","last_name":"Harris","age":23,"city":"Wrocław","district":"Stabłowice","glasses":true},
    {"id":9,"team":1,"first_name":"Phyllis","last_name":"Webb","age":19,"city":"Wrocław","district":"Leśnica","glasses":true},
    {"id":10,"team":1,"first_name":"Roger","last_name":"Alvarez","age":24,"city":"Wrocław","district":"Mokra","glasses":true},
    {"id":11,"team":2,"first_name":"Maria","last_name":"Carpenter","age":45,"city":"Wrocław","district":"Ołtaszyn","glasses":true},
    {"id":12,"team":2,"first_name":"Lori","last_name":"Edwards","age":60,"city":"Wrocław","district":"Klecina","glasses":true},
    {"id":13,"team":2,"first_name":"Phillip","last_name":"Mitchell","age":46,"city":"Wrocław","district":"Popowice","glasses":false},
    {"id":14,"team":2,"first_name":"Craig","last_name":"Lopez","age":37,"city":"Wrocław","district":"Osobowice","glasses":true},
    {"id":15,"team":2,"first_name":"Marie","last_name":"George","age":38,"city":"Wrocław","district":"Pawłowice","glasses":true},
    {"id":16,"team":2,"first_name":"Jean","last_name":"Duncan","age":14,"city":"Wrocław","district":"Zakrzów","glasses":true},
    {"id":17,"team":2,"first_name":"Kimberly","last_name":"Butler","age":17,"city":"Wrocław","district":"Psie pole","glasses":false},
    {"id":18,"team":2,"first_name":"Heather","last_name":"Ramirez","age":23,"city":"Wrocław","district":"Wojnów","glasses":false},
    {"id":19,"team":2,"first_name":"Jason","last_name":"Sanders","age":28,"city":"Wrocław","district":"Strachocin","glasses":false},
    {"id":20,"team":2,"first_name":"Juan","last_name":"Evans","age":39,"city":"Wrocław","district":"Wojnów","glasses":true},
    {"id":21,"team":3,"first_name":"Billy","last_name":"Tucker","age":42,"city":"Wrocław","district":"Psie pole","glasses":false},
    {"id":22,"team":3,"first_name":"Fred","last_name":"Duncan","age":32,"city":"Wrocław","district":"Widawa","glasses":true},
    {"id":23,"team":3,"first_name":"Daniel","last_name":"Peterson","age":20,"city":"Wrocław","district":"Rędzin","glasses":false},
    {"id":24,"team":3,"first_name":"Kelly","last_name":"Gilbert","age":19,"city":"Wrocław","district":"Ratyń","glasses":false},
    {"id":25,"team":3,"first_name":"Aaron","last_name":"Hart","age":18,"city":"Wrocław","district":"Polanowice","glasses":false},
    {"id":26,"team":3,"first_name":"Phillip","last_name":"Cook","age":18,"city":"Wrocław","district":"Kleczków","glasses":true},
    {"id":27,"team":3,"first_name":"Sara","last_name":"Perry","age":76,"city":"Wrocław","district":"Plac Grunwaldzki","glasses":false},
    {"id":28,"team":3,"first_name":"Karen","last_name":"Fields","age":64,"city":"Wrocław","district":"Plac Grunwaldzki","glasses":false},
    {"id":29,"team":3,"first_name":"Nancy","last_name":"Schmidt","age":34,"city":"Wrocław","district":"Stare Miasto","glasses":true},
    {"id":30,"team":6,"first_name":"Theresa","last_name":"Chavez","age":35,"city":"Wrocław","district":"Karłowice","glasses":true},
    {"id":31,"team":6,"first_name":"Howard","last_name":"Crawford","age":32,"city":"Wrocław","district":"Kowale","glasses":false},
    {"id":32,"team":6,"first_name":"Catherine","last_name":"Johnson","age":52,"city":"Wrocław","district":"Kuźniki","glasses":true},
    {"id":33,"team":6,"first_name":"Nicholas","last_name":"Morales","age":54,"city":"Wrocław","district":"Kowale","glasses":false},
    {"id":34,"team":6,"first_name":"Chris","last_name":"Morales","age":53,"city":"Wrocław","district":"Krzyki","glasses":true},
    {"id":35,"team":6,"first_name":"Mildred","last_name":"Frazier","age":55,"city":"Wrocław","district":"Świniary","glasses":true},
    {"id":36,"team":6,"first_name":"Mark","last_name":"Harper","age":56,"city":"Wrocław","district":"Krzyki","glasses":false},
    {"id":37,"team":6,"first_name":"Michael","last_name":"Ryan","age":57,"city":"Wrocław","district":"Zacisze","glasses":true},
    {"id":38,"team":6,"first_name":"Matthew","last_name":"Ruiz","age":70,"city":"Wrocław","district":"Sołtysowice","glasses":true},
    {"id":39,"team":6,"first_name":"Jose","last_name":"Morales","age":37,"city":"Wrocław","district":"Zalesie","glasses":true},
    {"id":40,"team":6,"first_name":"Scott","last_name":"Simpson","age":32,"city":"Wrocław","district":"Zgorzelisko","glasses":true},
    {"id":41,"team":4,"first_name":"Pamela","last_name":"Welch","age":12,"city":"Wrocław","district":"Kłokoczyce","glasses":false},
    {"id":42,"team":4,"first_name":"Ruth","last_name":"Mcdonald","age":17,"city":"Wrocław","district":"Psie pole","glasses":false},
    {"id":43,"team":4,"first_name":"Kevin","last_name":"Fields","age":28,"city":"Wrocław","district":"Kozanów","glasses":true},
    {"id":44,"team":4,"first_name":"Justin","last_name":"Kim","age":27,"city":"Wrocław","district":"Ratyń","glasses":true},
    {"id":45,"team":4,"first_name":"Wanda","last_name":"Jones","age":30,"city":"Wrocław","district":"Karłowice","glasses":true},
    {"id":46,"team":4,"first_name":"Jose","last_name":"Carter","age":48,"city":"Wrocław","district":"Klecina","glasses":false},
    {"id":47,"team":4,"first_name":"Joe","last_name":"Gonzales","age":49,"city":"Wrocław","district":"Partynice","glasses":true},
    {"id":48,"team":4,"first_name":"Martin","last_name":"Thompson","age":53,"city":"Wrocław","district":"Brochów","glasses":true},
    {"id":49,"team":4,"first_name":"Phillip","last_name":"Hayes","age":61,"city":"Wrocław","district":"Bieńkowice","glasses":true},
    {"id":50,"team":4,"first_name":"Angela","last_name":"Shaw","age":62,"city":"Wrocław","district":"Ołtaszyn","glasses":true},
    {"id":51,"team":5,"first_name":"Jimmy","last_name":"Garza","age":63,"city":"Wrocław","district":"Jagodno","glasses":true},
    {"id":52,"team":5,"first_name":"Doris","last_name":"Cook","age":66,"city":"Wrocław","district":"Złotniki","glasses":false},
    {"id":53,"team":5,"first_name":"Nancy","last_name":"Thompson","age":67,"city":"Wrocław","district":"Nowy dwór","glasses":true},
    {"id":54,"team":5,"first_name":"Sarah","last_name":"Stanley","age":78,"city":"Wrocław","district":"Mokra","glasses":false},
    {"id":55,"team":5,"first_name":"Douglas","last_name":"Gardner","age":32,"city":"Wrocław","district":"Widawa","glasses":true},
    {"id":56,"team":5,"first_name":"Mark","last_name":"Thomas","age":42,"city":"Wrocław","district":"Poświętne","glasses":false},
    {"id":57,"team":5,"first_name":"Judith","last_name":"Jenkins","age":49,"city":"Wrocław","district":"Plac Grunwaldzki","glasses":true},
    {"id":58,"team":5,"first_name":"Henry","last_name":"Ross","age":19,"city":"Wrocław","district":"Zakrzów","glasses":false},
    {"id":59,"team":5,"first_name":"Kimberly","last_name":"Gomez","age":20,"city":"Wrocław","district":"Żerniki","glasses":false},
    {"id":60,"team":5,"first_name":"Pamela","last_name":"Nelson","age":31,"city":"Wrocław","district":"Wojszyce","glasses":false}
    ];

export default peoples;